## Bài 1 Tạo Tensor cơ bản

Tạo một Tensor số nguyên kích thước 2 × 3 và hiển thị kết quả.

In [52]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


Yêu cầu: Cho biết kích thước, số chiều và kiểu dữ liệu của Tensor a.

#Bài 2. Tạo các Tensor thường dùng

Thực hành tạo Tensor ngẫu nhiên, Tensor toàn số 0, toàn số 1 và ma trận đơn vị.

In [53]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.1089, 0.6034, 0.0260, 0.4589],
        [0.7807, 0.4572, 0.9018, 0.2246],
        [0.0530, 0.5189, 0.7452, 0.7223]])
tensor([[-0.9392, -0.9804,  0.0875, -0.2255],
        [ 1.6364, -0.7082,  0.7536,  0.1799],
        [-1.8703,  0.9113, -0.0700,  0.4008]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


Yêu cầu:

• Nhận xét sự khác nhau giữa torch.rand() và torch.randn().


• Tạo thêm một Tensor 5 × 5 chứa toàn giá trị 10.

#Bài 3. Kiểm tra thông tin Tensor

Sử dụng shape, size(), ndim và dtype để kiểm tra các thuộc tính của Tensor.

In [54]:
import torch
a = torch.zeros(2, 3, 4)

print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


Yêu cầu: Giải thích ý nghĩa của torch.Size([2, 3, 4]).

#Bài 4. Slicing và Indexing

Truy xuất một phần dữ liệu từ Tensor nhiều chiều.

In [55]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[-1.1404e+00,  6.0634e-01,  2.1203e+00, -2.6387e+00,  1.3424e+00],
         [ 2.9344e-01,  1.3271e+00,  2.3444e-03, -1.1625e-01, -9.8381e-02],
         [ 4.7041e-01,  8.0552e-01,  8.4858e-02,  2.3953e+00,  1.8619e+00],
         [-1.1626e+00,  3.2550e-02, -1.1605e+00, -2.7950e-01,  1.3811e+00]],

        [[ 1.0667e+00,  1.4698e+00,  8.8265e-03, -1.5059e+00,  9.5658e-01],
         [-1.1300e+00, -1.1509e+00,  1.3368e+00, -3.4876e-02,  7.1300e-01],
         [ 2.6640e+00,  7.3936e-01,  2.8516e-02,  9.2182e-01,  8.8616e-02],
         [ 4.6779e-01, -7.3737e-03,  9.1457e-01, -6.4746e-01, -3.5061e-01]],

        [[-4.3891e-01,  4.5668e-01,  6.8385e-01, -1.0224e+00,  1.2603e+00],
         [-9.5505e-01,  2.2935e-01,  5.0002e-03,  9.4955e-01,  3.7927e-01],
         [ 2.0052e-01,  9.7470e-01, -1.3985e+00, -1.1102e+00,  7.8070e-01],
         [ 3.5797e-01, -7.5457e-02,  1.4699e+00,  5.3026e-01,  9.4493e-01]]])

Tensor a[1]:
tensor([[ 1.0667,  1.4698,  0.0088, -1.5059,  0.956

Yêu cầu:


• Cho biết shape của a[1] và a[1:, 2:4].


• Thử lấy hai phần tử cuối cùng trên chiều thứ ba.

#Bài 5. Reshape và Flatten

Thay đổi hình dạng Tensor mà không làm thay đổi số phần tử.

In [56]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[-1.3675,  0.6108,  0.1168,  0.7184],
        [-1.4465, -0.5259,  0.2260, -1.6060],
        [-0.7157, -0.5809,  1.3106,  0.7484]])

Flatten:
tensor([-1.3675,  0.6108,  0.1168,  0.7184, -1.4465, -0.5259,  0.2260, -1.6060,
        -0.7157, -0.5809,  1.3106,  0.7484])

Reshape to 3 x 2 x 2:
tensor([[[-1.3675,  0.6108],
         [ 0.1168,  0.7184]],

        [[-1.4465, -0.5259],
         [ 0.2260, -1.6060]],

        [[-0.7157, -0.5809],
         [ 1.3106,  0.7484]]])


Yêu cầu:


• Kiểm tra số phần tử trước và sau khi reshape.


• Thử reshape Tensor thành kích thước 2 × 6.

#Bài 6. Phép toán và nhân ma trận

Thực hiện các phép toán phần tử và phép nhân ma trận bằng toán tử @.

In [57]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)

print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[ 1.7705, -0.0101,  0.4732],
        [ 0.0952,  1.1044,  1.2050]])
b:
tensor([[ 0.7889,  0.8692, -0.1969],
        [-0.7001,  0.2048,  0.4258]])

a + b:
tensor([[ 2.5594,  0.8590,  0.2763],
        [-0.6049,  1.3091,  1.6308]])

a / b:
tensor([[ 2.2443, -0.0117, -2.4033],
        [-0.1359,  5.3937,  2.8299]])

a^2:
tensor([[3.1347e+00, 1.0288e-04, 2.2393e-01],
        [9.0552e-03, 1.2197e+00, 1.4520e+00]])

Matrix multiplication:
tensor([[ 1.2948, -1.0401],
        [ 0.7977,  0.6726]])


Yêu cầu:


• Phân biệt phép toán a * b với a @ b.T.


• Cho biết shape của kết quả a @ b.T.

#Bài 7. Các hàm thống kê trên Tensor

Tính trung bình, độ lệch chuẩn và tổng tích lũy theo từng cột.

In [58]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[ 1.6097, -1.9317,  1.7827,  0.2123],
        [ 0.6626,  0.4642,  0.8821, -1.6287],
        [-1.3231, -1.4636,  1.3318, -1.5842]])

Mean:
tensor([ 0.3164, -0.9770,  1.3322, -1.0002])

Standard deviation:
tensor([1.4967, 1.2699, 0.4503, 1.0503])

Cumulative sum:
tensor([[ 1.6097, -1.9317,  1.7827,  0.2123],
        [ 2.2722, -1.4674,  2.6649, -1.4165],
        [ 0.9491, -2.9310,  3.9967, -3.0007]])


Yêu cầu:
• Thay dim=0 bằng dim=1 và nhận xét sự khác nhau.

#Bài 8. Autograd cơ bản

Tạo biến có requires_grad=True và dùng backward() để tính đạo hàm tự động.

In [59]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


Yêu cầu:


• Tính thủ công đạo hàm của y = x2 tại x = 3.6 và so sánh với x.grad.


• Đổi hàm thành y = 3*x**2 + 2*x + 1 và kiểm tra gradient.

#Bài 9. Gradient Descent tìm hệ số đa thức

Sinh dữ liệu từ đa thức y = x2 + 2x + 3, sau đó dùng NAdam và autograd để tìm lại ba hệ số.

In [60]:
import numpy as np
import torch
polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
X * X,
X,
np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)
for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[-0.6247],
        [ 1.1649],
        [ 0.4235]], requires_grad=True)
Learned coefficients:
tensor([[1.0059],
        [2.0024],
        [2.3614]], requires_grad=True)


Yêu cầu:


• So sánh ba hệ số học được với [1, 2, 3].



• Giải thích vai trò của optimizer.zero_grad(), mse.backward() và optimizer.step().

#Bài 10. Giải hệ phương trình bằng Autograd

Tối thiểu hóa tổng sai số bình phương để tìm A, B, C, D thỏa bốn phương trình.

In [64]:
import random
import torch
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)
for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(5.0409, requires_grad=True)
B = tensor(3.9590, requires_grad=True)
C = tensor(2.9591, requires_grad=True)
D = tensor(1.9590, requires_grad=True)


Yêu cầu:

• Kiểm tra nghiệm thu được với bốn phương trình: A+B=9, C-D=1, A+C=8, B-D=2.

• Nhận xét vì sao bài toán có thể có nhiều nghiệm.

#Bài 11. Viết chương trình PyTorch để thực hiện các yêu cầu sau:

1. Tensor X 24 phần tử, reshape thành 4x6, 2x12, 2x3x4

In [66]:
import torch

torch.manual_seed(42)


print("CÂU 1: Tạo Tensor X (24 phần tử) và reshape")


# Tạo tensor X có 24 phần tử (0..23)
X = torch.arange(24)
print("X gốc (24 phần tử):\n", X)

X_4x6 = X.reshape(4, 6)
X_2x12 = X.reshape(2, 12)
X_2x3x4 = X.reshape(2, 3, 4)

print("\nX reshape (4, 6):\n", X_4x6)
print("\nX reshape (2, 12):\n", X_2x12)
print("\nX reshape (2, 3, 4):\n", X_2x3x4)


CÂU 1: Tạo Tensor X (24 phần tử) và reshape
X gốc (24 phần tử):
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

X reshape (4, 6):
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

X reshape (2, 12):
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

X reshape (2, 3, 4):
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


Tạo hai Tensor A, B kích thước 3 × 4; tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột.

In [67]:
print("CÂU 2: Tensor A, B (3x4) - các phép toán và thống kê theo cột")


# Tạo A, B ngẫu nhiên kích thước 3x4 (dùng số dương để tránh chia cho 0)
A = torch.rand(3, 4) * 10 + 1   # giá trị trong khoảng [1, 11)
B = torch.rand(3, 4) * 10 + 1

print("A =\n", A)
print("\nB =\n", B)

A_plus_B = A + B
A_times_B = A * B          # nhân element-wise (không phải nhân ma trận)
A_div_B = A / B

print("\nA + B =\n", A_plus_B)
print("\nA * B (element-wise) =\n", A_times_B)
print("\nA / B =\n", A_div_B)

# Trung bình và độ lệch chuẩn theo CỘT -> tính theo chiều dim=0 (giảm theo hàng)
mean_col_A = A.mean(dim=0)
std_col_A = A.std(dim=0)
mean_col_B = B.mean(dim=0)
std_col_B = B.std(dim=0)

print("\nTrung bình theo cột của A:", mean_col_A)
print("Độ lệch chuẩn theo cột của A:", std_col_A)
print("\nTrung bình theo cột của B:", mean_col_B)
print("Độ lệch chuẩn theo cột của B:", std_col_B)

CÂU 2: Tensor A, B (3x4) - các phép toán và thống kê theo cột
A =
 tensor([[ 9.8227, 10.1500,  4.8286, 10.5931],
        [ 4.9045,  7.0090,  3.5657,  8.9364],
        [10.4077,  2.3319, 10.3460,  6.9358]])

B =
 tensor([[9.6940, 6.6772, 8.4109, 5.2940],
        [9.8544, 6.7390, 3.6658, 7.2745],
        [3.6963, 5.4136, 3.9692, 9.3169]])

A + B =
 tensor([[19.5167, 16.8272, 13.2396, 15.8871],
        [14.7589, 13.7480,  7.2315, 16.2109],
        [14.1040,  7.7455, 14.3152, 16.2527]])

A * B (element-wise) =
 tensor([[95.2216, 67.7734, 40.6134, 56.0801],
        [48.3309, 47.2337, 13.0712, 65.0079],
        [38.4702, 12.6238, 41.0654, 64.6198]])

A / B =
 tensor([[1.0133, 1.5201, 0.5741, 2.0009],
        [0.4977, 1.0401, 0.9727, 1.2285],
        [2.8157, 0.4307, 2.6066, 0.7444]])

Trung bình theo cột của A: tensor([8.3783, 6.4970, 6.2468, 8.8218])
Độ lệch chuẩn theo cột của A: tensor([3.0226, 3.9342, 3.6057, 1.8313])

Trung bình theo cột của B: tensor([7.7483, 6.2766, 5.3486, 7.2951])
Độ

In [68]:

print("CÂU 3: Autograd - y = 2x^2 + 5x + 3, tính dy/dx tại x = 2")


x = torch.tensor(2.0, requires_grad=True)
y = 2 * x**2 + 5 * x + 3

y.backward()  # tính đạo hàm dy/dx tự động

dy_dx_autograd = x.grad.item()
print(f"y tại x=2: {y.item()}")
print(f"dy/dx (autograd) tại x=2: {dy_dx_autograd}")

# Kiểm tra thủ công: dy/dx = 4x + 5 -> tại x=2: 4*2 + 5 = 13
dy_dx_manual = 4 * 2 + 5
print(f"dy/dx (tính tay) = 4x + 5 tại x=2: {dy_dx_manual}")
print(f"Khớp nhau? {'Có' if abs(dy_dx_autograd - dy_dx_manual) < 1e-6 else 'Không'}")

CÂU 3: Autograd - y = 2x^2 + 5x + 3, tính dy/dx tại x = 2
y tại x=2: 21.0
dy/dx (autograd) tại x=2: 13.0
dy/dx (tính tay) = 4x + 5 tại x=2: 13
Khớp nhau? Có


In [71]:

print("CÂU 4: Thay đa thức bằng y = 2x^2 - 3x + 5, huấn luyện tìm hệ số")


# Sinh dữ liệu từ đa thức thật: y = 2x^2 - 3x + 5 (+ nhiễu nhỏ)
true_a, true_b, true_c = 2.0, -3.0, 5.0

x_data = torch.linspace(-5, 5, 200).reshape(-1, 1)
noise = torch.randn(x_data.shape) * 0.5
y_data = true_a * x_data**2 + true_b * x_data + true_c + noise

# Khởi tạo hệ số cần học: a, b, c (ngẫu nhiên, có requires_grad=True)
a = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)
c = torch.randn(1, requires_grad=True)

optimizer = torch.optim.SGD([a, b, c], lr=0.001)
n_epochs = 3000

for epoch in range(n_epochs):
    optimizer.zero_grad()

    y_pred = a * x_data**2 + b * x_data + c
    loss = torch.mean((y_pred - y_data) ** 2)  # MSE

    loss.backward()
    optimizer.step()

    if (epoch + 1) % 500 == 0:
        print(f"Epoch {epoch+1}/{n_epochs} - Loss: {loss.item():.4f} "
              f"- a={a.item():.4f}, b={b.item():.4f}, c={c.item():.4f}")

print("\nKết quả cuối cùng ")
print(f"Hệ số thật:   a = {true_a}, b = {true_b}, c = {true_c}")
print(f"Hệ số học được: a = {a.item():.4f}, b = {b.item():.4f}, c = {c.item():.4f}")

CÂU 4: Thay đa thức bằng y = 2x^2 - 3x + 5, huấn luyện tìm hệ số
Epoch 500/3000 - Loss: 3.6682 - a=2.1809, b=-2.9980, c=2.2100
Epoch 1000/3000 - Loss: 1.6734 - a=2.1154, b=-2.9984, c=3.1978
Epoch 1500/3000 - Loss: 0.8504 - a=2.0734, b=-2.9984, c=3.8323
Epoch 2000/3000 - Loss: 0.5109 - a=2.0464, b=-2.9984, c=4.2399
Epoch 2500/3000 - Loss: 0.3708 - a=2.0291, b=-2.9984, c=4.5017
Epoch 3000/3000 - Loss: 0.3130 - a=2.0179, b=-2.9984, c=4.6698

Kết quả cuối cùng 
Hệ số thật:   a = 2.0, b = -3.0, c = 5.0
Hệ số học được: a = 2.0179, b = -2.9984, c = 4.6698
